# Generated by Django 5.2.3 on 2025-12-02 00:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المديرية')),
                ('state', models.CharField(max_length=100, verbose_name='العزلة')),
                ('country', models.CharField(max_length=100, verbose_name='القرية')),
            ],
            options={
                'verbose_name': 'العنوان',
                'verbose_name_plural': 'العناوين',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الأب')),
                ('third_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الثالث')),
                ('forth_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الرابع')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
            ],
            options={
                'verbose_name': 'الاسم الكامل',
                'verbose_name_plural': 'الأسماء الكاملة',
            },
        ),
        migrations.CreateModel(
            name='Name_covenants_covenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_covenants_covenant', models.CharField(max_length=100, verbose_name='اسم العهدة')),
            ],
            options={
                'verbose_name': 'العهدة',
                'verbose_name_plural': 'أسماء العهد',
            },
        ),
        migrations.CreateModel(
            name='PersonalIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, verbose_name='رقم البطاقة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('governorate', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='المديرية')),
                ('sub_district', models.CharField(blank=True, max_length=50, null=True, verbose_name='العزلة')),
                ('village', models.CharField(blank=True, max_length=50, null=True, verbose_name='القرية')),
                ('blood_Type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True, verbose_name='فصيلة الدم')),
            ],
            options={
                'verbose_name': 'بطاقة الهوية الشخصية',
                'verbose_name_plural': 'بطاقات الهوية الشخصية',
            },
        ),
        migrations.CreateModel(
            name='Semester_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_semester', models.CharField(max_length=100, verbose_name=' الفصل')),
            ],
            options={
                'verbose_name': 'الفصل الدراسي ',
                'verbose_name_plural': 'الفصول الدراسية ',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'التخصص',
                'verbose_name_plural': 'التخصصات',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المادة')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Type_covenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name_covenants', models.CharField(max_length=100, verbose_name='نوع العهدة')),
            ],
            options={
                'verbose_name': 'العهدة',
                'verbose_name_plural': 'أنواع العهد',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='اسم الجامعة')),
            ],
            options={
                'verbose_name': 'الجامعة',
                'verbose_name_plural': 'الجامعات',
            },
        ),
        migrations.CreateModel(
            name='Year_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_year', models.CharField(max_length=100, verbose_name='السنة ')),
            ],
            options={
                'verbose_name': 'السنة الدراسية ',
                'verbose_name_plural': 'السنوات الدراسية ',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدخول')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دخول وخروج',
                'verbose_name_plural': 'الدخول والخروج',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='الكنية')),
                ('military_number', models.IntegerField(blank=True, null=True, verbose_name='الرقم العسكري')),
                ('jihadist_number', models.IntegerField(blank=True, null=True, verbose_name='الرقم الجهادي')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('typestatus', models.CharField(choices=[('متوقف', 'متوقف'), ('ليس متوقف', 'ليس متوقف')], default='ليس متوقف', max_length=20, verbose_name='التوقف ')),
                ('stop_reason', models.TextField(blank=True, null=True, verbose_name='سبب التوقف')),
                ('academic_qualification', models.CharField(blank=True, choices=[('بدون مؤهل', 'بدون مؤهل'), ('ثانوي', 'ثانوي'), ('دبلوم مهني', 'دبلوم مهني'), ('دبلوم جامعي', 'دبلوم جامعي'), ('بكالوريوس', 'بكالوريوس'), ('دبلوم عالي', 'دبلوم عالي'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه'), ('أستاذ دكتور', 'أستاذ دكتور')], max_length=50, null=True, verbose_name='المؤهل العلمي')),
                ('high_school_grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='معدل الثانوية العامة')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True, verbose_name='المشرف')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('Section', models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم')),
                ('Polarized_sid', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهه المستقطبه')),
                ('status', models.CharField(blank=True, choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('ضعيف', 'ضعيف'), ('فقير جدًا', 'فقير جدًا'), ('يتيم', 'يتيم')], max_length=100, null=True, verbose_name='الحالة المادية')),
                ('male_children', models.PositiveIntegerField(blank=True, default='لايوجد', null=True, verbose_name='عدد الأولاد الذكور')),
                ('female_children', models.PositiveIntegerField(blank=True, default='لايوجد', null=True, verbose_name='عدد الأولاد الإناث')),
                ('total_children', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='إجمالي الأولاد')),
                ('marital_status', models.CharField(blank=True, choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=50, null=True, verbose_name='الحالة الاجتماعية')),
                ('health_condition', models.CharField(blank=True, choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('سيئ', 'سيئ'), ('ذو إعاقة', 'ذو إعاقة'), ('مريض مزمن', 'مريض مزمن')], max_length=255, null=True, verbose_name='الحالة الصحية')),
                ('batch', models.CharField(blank=True, choices=[('الأولى', 'الأولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة'), ('الخامسة', 'الخامسة'), ('السادسة', 'السادسة'), ('السابعة', 'السابعة'), ('الثامنة', 'الثامنة'), ('التاسعة', 'التاسعة'), ('العاشرة', 'العاشرة')], max_length=10, null=True, verbose_name='الدفعة')),
                ('is_present', models.BooleanField(default=True, verbose_name='متواجد')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.address', verbose_name='العنوان')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='الاسم')),
                ('national_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='HR.personalidcard', verbose_name='البطاقة الشخصية')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.IntegerField(blank=True, null=True, verbose_name='الإعتمادية')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='رعاية')),
                ('visit', models.IntegerField(blank=True, null=True, verbose_name='مزاورة')),
                ('expenses', models.IntegerField(blank=True, null=True, verbose_name='مصروف جيب')),
                ('transfers', models.IntegerField(blank=True, null=True, verbose_name='تنقلات')),
                ('qat', models.IntegerField(blank=True, null=True, verbose_name='قات')),
                ('help', models.IntegerField(blank=True, null=True, verbose_name='مساعدة')),
                ('rent', models.IntegerField(blank=True, null=True, verbose_name='إيجار')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'إعتماد مالي',
                'verbose_name_plural': ' الأعتمادية المالية',
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('سليم', 'سليم'), ('مريض', 'مريض'), ('حالة حرجة', 'حالة حرجة'), ('إصابات أخرى', 'إصابات أخرى'), ('غير محدد', 'غير محدد')], max_length=100, verbose_name='الحالة الصحية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='خلاصة عن الأمراض')),
                ('type_sex', models.TextField(blank=True, null=True, verbose_name=' نوع المرض')),
                ('medicines', models.TextField(blank=True, null=True, verbose_name='العلاجات')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'العلاج',
                'verbose_name_plural': 'العلاجات',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدورة')),
                ('entity', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='السنة ')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='النتيجة')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'دورة تطويرية',
                'verbose_name_plural': 'الدورات التطويرية',
            },
        ),
        migrations.CreateModel(
            name='Covenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'العهدة',
                'verbose_name_plural': 'العهد',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('session', models.BooleanField(default=False, verbose_name='حاضر')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'الحضور اليومي',
                'verbose_name_plural': 'الحضور اليومي',
            },
        ),
        migrations.CreateModel(
            name='AcademicCoursePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدورة')),
                ('entity', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='السنة ')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='النتيجة')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'دورة أكاديمية',
                'verbose_name_plural': 'الدورات الإكاديمية',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='المؤهل')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤسسة التعليمية')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='سنة التخرج')),
                ('avarg', models.IntegerField(blank=True, null=True, verbose_name='المعدل ')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='التقدير')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'مؤهل أكاديمي',
                'verbose_name_plural': 'المؤهلات الأكاديمية',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='العمل')),
                ('text_notes', models.TextField(blank=True, null=True, verbose_name='المهام الموكلة ')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('continue_work', models.BooleanField(default=True, verbose_name='استمرار العمل')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('stop_reason', models.TextField(blank=True, null=True, verbose_name='سبب الانتهاء')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العاملين',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnyear', models.CharField(choices=[('الأولى', 'الأولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة'), ('خريج', 'خريج')], max_length=10, verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('stop_reason', models.TextField(blank=True, null=True, verbose_name=' سبب الانتهاء')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.specialization', verbose_name='التخصص')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_year', models.CharField(choices=[('الأولى', 'الأولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة'), ('خريج', 'خريج')], max_length=10, verbose_name='السنة')),
                ('semester', models.CharField(blank=True, choices=[('الأول', 'الأول'), ('الثاني', 'الثاني')], max_length=10, null=True, verbose_name='الترم')),
                ('mrak_of_subject', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('enrollment_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ التسجيل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.subject', verbose_name='المادة الدراسية')),
            ],
            options={
                'verbose_name': 'إضافة مادة للطالب',
                'verbose_name_plural': 'إضافة مواد للطالب',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='المهمة')),
                ('priority', models.CharField(choices=[('عالي', 'عالي'), ('متوسط', 'متوسط'), ('منخفض', 'منخفض')], default='متوسط', max_length=10, verbose_name='الأولوية')),
                ('type', models.CharField(choices=[('مالية', 'مالية'), ('إدارية', 'إدارية'), ('تجهيزات', 'تجهيزات'), ('لوجستي', 'لوجستي')], max_length=50, verbose_name='النوع')),
                ('urgency_score', models.IntegerField(default=0, verbose_name='النقاط')),
                ('status', models.CharField(choices=[('تم', 'تم'), ('لم يتم', 'لم يتم')], default='لم يتم', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='الوقت')),
                ('result', models.CharField(blank=True, max_length=200, null=True, verbose_name='النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الإنشاء')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_delegate', to='HR.name', verbose_name='المكلف')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_follower', to='HR.name', verbose_name='المتابع')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='المادة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('mark', models.CharField(blank=True, max_length=50, null=True, verbose_name='النتيجة / التقييم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('people', models.ManyToManyField(blank=True, to='HR.person', verbose_name='المتدربون')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='المدرب')),
            ],
            options={
                'verbose_name': 'المدرب',
                'verbose_name_plural': 'المدربون',
            },
        ),
        migrations.CreateModel(
            name='Name_covenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='_____الكمية___')),
                ('name', models.CharField(choices=[('معه', 'معه'), ('لم يتم ارجاعها', 'لم يتم ارجاعها')], max_length=50, verbose_name='العهدة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام ')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرجوع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('covenantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.covenant', verbose_name='الشخص')),
                ('name_covenants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.name_covenants_covenants', verbose_name='اسم العهدة')),
                ('type_covenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.type_covenants', verbose_name='نوع العهدة')),
            ],
            options={
                'verbose_name': 'العهدة',
                'verbose_name_plural': 'أسماء العهد',
            },
        ),
        migrations.CreateModel(
            name='Violation_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'مخالفة',
                'verbose_name_plural': 'مخالفات',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('violation_type', models.CharField(choices=[('إنذار شفوي', 'إنذار شفوي'), ('لفت نظر', 'لفت نظر'), ('إنذار خطي', 'إنذار خطي'), ('إنذار نهائي', 'إنذار نهائي')], max_length=100, verbose_name='نوع المخالفة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('action_taken', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإجراء المتخذ')),
                ('resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
                ('violation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='HR.violation_name', verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'تفاصيل مخالفة',
                'verbose_name_plural': 'تفاصيل المخالفات',
            },
        ),
        migrations.CreateModel(
            name='WorshipSideSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'جانب ثقافي ',
                'verbose_name_plural': 'الجانب الثقافي',
            },
        ),
        migrations.CreateModel(
            name='StrengthAndWeaknessSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(blank=True, choices=[(1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449'), (1450, '1450'), (1451, '1451'), (1452, '1452'), (1453, '1453'), (1454, '1454'), (1455, '1455'), (1456, '1456'), (1457, '1457'), (1458, '1458'), (1459, '1459'), (1460, '1460'), (1461, '1461'), (1462, '1462'), (1463, '1463'), (1464, '1464'), (1465, '1465'), (1466, '1466'), (1467, '1467'), (1468, '1468'), (1469, '1469'), (1470, '1470'), (1471, '1471'), (1472, '1472'), (1473, '1473'), (1474, '1474'), (1475, '1475'), (1476, '1476'), (1477, '1477'), (1478, '1478'), (1479, '1479'), (1480, '1480'), (1481, '1481'), (1482, '1482'), (1483, '1483'), (1484, '1484'), (1485, '1485'), (1486, '1486'), (1487, '1487'), (1488, '1488'), (1489, '1489'), (1490, '1490'), (1491, '1491'), (1492, '1492'), (1493, '1493'), (1494, '1494'), (1495, '1495'), (1496, '1496'), (1497, '1497'), (1498, '1498'), (1499, '1499'), (1500, '1500')], null=True, verbose_name='السنة الهجرية')),
                ('gregorian_year', models.PositiveIntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True, verbose_name='السنة الميلادية')),
                ('hijri_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'محرم'), (2, 'صفر'), (3, 'ربيع الأول'), (4, 'ربيع الآخر'), (5, 'جمادى الأولى'), (6, 'جمادى الآخرة'), (7, 'رجب'), (8, 'شعبان'), (9, 'رمضان'), (10, 'شوال'), (11, 'ذو القعدة'), (12, 'ذو الحجة')], null=True, verbose_name='الشهر الهجري')),
                ('gregorian_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر الميلادي')),
                ('Power', models.TextField(blank=True, null=True, verbose_name='مواطن القوة')),
                ('Weakness', models.TextField(blank=True, null=True, verbose_name='مواطن الضعف')),
                ('Suggestions_and_Recommendations', models.TextField(blank=True, null=True, verbose_name='المقترحات والتوصيات العامة لتطوير قدراته')),
                ('worship_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_weakness', to='HR.worshipsidesecond')),
            ],
            options={
                'verbose_name': 'مواطن قوة ومواطن ضعف',
                'verbose_name_plural': 'مواطن قوة ومواطن ضعف',
            },
        ),
        migrations.CreateModel(
            name='GeneralNotesSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(blank=True, choices=[(1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449'), (1450, '1450'), (1451, '1451'), (1452, '1452'), (1453, '1453'), (1454, '1454'), (1455, '1455'), (1456, '1456'), (1457, '1457'), (1458, '1458'), (1459, '1459'), (1460, '1460'), (1461, '1461'), (1462, '1462'), (1463, '1463'), (1464, '1464'), (1465, '1465'), (1466, '1466'), (1467, '1467'), (1468, '1468'), (1469, '1469'), (1470, '1470'), (1471, '1471'), (1472, '1472'), (1473, '1473'), (1474, '1474'), (1475, '1475'), (1476, '1476'), (1477, '1477'), (1478, '1478'), (1479, '1479'), (1480, '1480'), (1481, '1481'), (1482, '1482'), (1483, '1483'), (1484, '1484'), (1485, '1485'), (1486, '1486'), (1487, '1487'), (1488, '1488'), (1489, '1489'), (1490, '1490'), (1491, '1491'), (1492, '1492'), (1493, '1493'), (1494, '1494'), (1495, '1495'), (1496, '1496'), (1497, '1497'), (1498, '1498'), (1499, '1499'), (1500, '1500')], null=True, verbose_name='السنة الهجرية')),
                ('gregorian_year', models.PositiveIntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True, verbose_name='السنة الميلادية')),
                ('hijri_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'محرم'), (2, 'صفر'), (3, 'ربيع الأول'), (4, 'ربيع الآخر'), (5, 'جمادى الأولى'), (6, 'جمادى الآخرة'), (7, 'رجب'), (8, 'شعبان'), (9, 'رمضان'), (10, 'شوال'), (11, 'ذو القعدة'), (12, 'ذو الحجة')], null=True, verbose_name='الشهر الهجري')),
                ('gregorian_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر الميلادي')),
                ('His_ethics', models.TextField(blank=True, null=True, verbose_name='-اخلاقه')),
                ('His_nature', models.TextField(blank=True, null=True, verbose_name='طبيعته')),
                ('Prepared_to_work', models.TextField(blank=True, null=True, verbose_name='استعداده للعمل في اي مجال او مكان او وقت ولفتره غير محددة')),
                ('worship_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='HR.worshipsidesecond')),
            ],
            options={
                'verbose_name': 'ملاحظه عامة',
                'verbose_name_plural': 'الملاحظات العامة',
            },
        ),
        migrations.CreateModel(
            name='CulturalSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(blank=True, choices=[(1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449'), (1450, '1450'), (1451, '1451'), (1452, '1452'), (1453, '1453'), (1454, '1454'), (1455, '1455'), (1456, '1456'), (1457, '1457'), (1458, '1458'), (1459, '1459'), (1460, '1460'), (1461, '1461'), (1462, '1462'), (1463, '1463'), (1464, '1464'), (1465, '1465'), (1466, '1466'), (1467, '1467'), (1468, '1468'), (1469, '1469'), (1470, '1470'), (1471, '1471'), (1472, '1472'), (1473, '1473'), (1474, '1474'), (1475, '1475'), (1476, '1476'), (1477, '1477'), (1478, '1478'), (1479, '1479'), (1480, '1480'), (1481, '1481'), (1482, '1482'), (1483, '1483'), (1484, '1484'), (1485, '1485'), (1486, '1486'), (1487, '1487'), (1488, '1488'), (1489, '1489'), (1490, '1490'), (1491, '1491'), (1492, '1492'), (1493, '1493'), (1494, '1494'), (1495, '1495'), (1496, '1496'), (1497, '1497'), (1498, '1498'), (1499, '1499'), (1500, '1500')], null=True, verbose_name='السنة الهجرية')),
                ('gregorian_year', models.PositiveIntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True, verbose_name='السنة الميلادية')),
                ('hijri_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'محرم'), (2, 'صفر'), (3, 'ربيع الأول'), (4, 'ربيع الآخر'), (5, 'جمادى الأولى'), (6, 'جمادى الآخرة'), (7, 'رجب'), (8, 'شعبان'), (9, 'رمضان'), (10, 'شوال'), (11, 'ذو القعدة'), (12, 'ذو الحجة')], null=True, verbose_name='الشهر الهجري')),
                ('gregorian_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر الميلادي')),
                ('seeking_forgi', models.IntegerField(verbose_name='استيعابه لهدى الله')),
                ('seeking_forgiveness', models.IntegerField(verbose_name='الوعي الثقافي')),
                ('congregational_prayer', models.IntegerField(verbose_name='تقبله وتفاعله مع هدى الله')),
                ('maintaining_prayer', models.IntegerField(verbose_name='الروحية الجهادية')),
                ('the_supplication', models.IntegerField(verbose_name='تقبله للتوجيهات ضمن المجموعة')),
                ('recitation_of_the_quran', models.IntegerField(verbose_name='تقبله لتوجيهات القائمين')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='الاجمالي')),
                ('worship_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural', to='HR.worshipsidesecond')),
            ],
            options={
                'verbose_name': 'ثقافي',
                'verbose_name_plural': 'الثقافي',
            },
        ),
        migrations.CreateModel(
            name='BehavioralSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(blank=True, choices=[(1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449'), (1450, '1450'), (1451, '1451'), (1452, '1452'), (1453, '1453'), (1454, '1454'), (1455, '1455'), (1456, '1456'), (1457, '1457'), (1458, '1458'), (1459, '1459'), (1460, '1460'), (1461, '1461'), (1462, '1462'), (1463, '1463'), (1464, '1464'), (1465, '1465'), (1466, '1466'), (1467, '1467'), (1468, '1468'), (1469, '1469'), (1470, '1470'), (1471, '1471'), (1472, '1472'), (1473, '1473'), (1474, '1474'), (1475, '1475'), (1476, '1476'), (1477, '1477'), (1478, '1478'), (1479, '1479'), (1480, '1480'), (1481, '1481'), (1482, '1482'), (1483, '1483'), (1484, '1484'), (1485, '1485'), (1486, '1486'), (1487, '1487'), (1488, '1488'), (1489, '1489'), (1490, '1490'), (1491, '1491'), (1492, '1492'), (1493, '1493'), (1494, '1494'), (1495, '1495'), (1496, '1496'), (1497, '1497'), (1498, '1498'), (1499, '1499'), (1500, '1500')], null=True, verbose_name='السنة الهجرية')),
                ('gregorian_year', models.PositiveIntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True, verbose_name='السنة الميلادية')),
                ('hijri_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'محرم'), (2, 'صفر'), (3, 'ربيع الأول'), (4, 'ربيع الآخر'), (5, 'جمادى الأولى'), (6, 'جمادى الآخرة'), (7, 'رجب'), (8, 'شعبان'), (9, 'رمضان'), (10, 'شوال'), (11, 'ذو القعدة'), (12, 'ذو الحجة')], null=True, verbose_name='الشهر الهجري')),
                ('gregorian_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر الميلادي')),
                ('waking_up_before_dawn', models.IntegerField(verbose_name='___احسانه')),
                ('seeking_forgiveness', models.IntegerField(verbose_name='الحكمه في التصرف')),
                ('congregational_prayer', models.IntegerField(verbose_name='انسجامه مع الزملاء')),
                ('maintaining_prayer', models.IntegerField(verbose_name='تاثيره على المجموعه')),
                ('the_supplication', models.IntegerField(verbose_name='مستوى التحسن والارتقاء في التصرف')),
                ('recitation_of_the_quran', models.IntegerField(verbose_name='الاهتمام بالنظافة')),
                ('the_glorification', models.IntegerField(verbose_name='مبادرته للعمل')),
                ('friday_prayer', models.IntegerField(verbose_name='اتقانه للعمل')),
                ('interacted_with_the_lieutenant', models.IntegerField(verbose_name='اهتمامه بالمظهر')),
                ('nteracted', models.IntegerField(verbose_name='التزامة وانضباطة')),
                ('Patience_and_endurance', models.IntegerField(verbose_name='الصبر والتحمل')),
                ('secrecy', models.IntegerField(verbose_name='___السرية')),
                ('Security_sense', models.IntegerField(verbose_name='الحس الامني')),
                ('Appraisal_of_Responsibility', models.IntegerField(verbose_name='تقدير المسئولية')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='الاجمالي')),
                ('worship_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral', to='HR.worshipsidesecond')),
            ],
            options={
                'verbose_name': 'سلوكي',
                'verbose_name_plural': 'السلوكي',
            },
        ),
        migrations.CreateModel(
            name='AssessmentMakerOpinionSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(blank=True, choices=[(1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449'), (1450, '1450'), (1451, '1451'), (1452, '1452'), (1453, '1453'), (1454, '1454'), (1455, '1455'), (1456, '1456'), (1457, '1457'), (1458, '1458'), (1459, '1459'), (1460, '1460'), (1461, '1461'), (1462, '1462'), (1463, '1463'), (1464, '1464'), (1465, '1465'), (1466, '1466'), (1467, '1467'), (1468, '1468'), (1469, '1469'), (1470, '1470'), (1471, '1471'), (1472, '1472'), (1473, '1473'), (1474, '1474'), (1475, '1475'), (1476, '1476'), (1477, '1477'), (1478, '1478'), (1479, '1479'), (1480, '1480'), (1481, '1481'), (1482, '1482'), (1483, '1483'), (1484, '1484'), (1485, '1485'), (1486, '1486'), (1487, '1487'), (1488, '1488'), (1489, '1489'), (1490, '1490'), (1491, '1491'), (1492, '1492'), (1493, '1493'), (1494, '1494'), (1495, '1495'), (1496, '1496'), (1497, '1497'), (1498, '1498'), (1499, '1499'), (1500, '1500')], null=True, verbose_name='السنة الهجرية')),
                ('gregorian_year', models.PositiveIntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True, verbose_name='السنة الميلادية')),
                ('hijri_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'محرم'), (2, 'صفر'), (3, 'ربيع الأول'), (4, 'ربيع الآخر'), (5, 'جمادى الأولى'), (6, 'جمادى الآخرة'), (7, 'رجب'), (8, 'شعبان'), (9, 'رمضان'), (10, 'شوال'), (11, 'ذو القعدة'), (12, 'ذو الحجة')], null=True, verbose_name='الشهر الهجري')),
                ('gregorian_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر الميلادي')),
                ('Assessment_maker_opinion', models.TextField(blank=True, null=True, verbose_name='رأي معد التقييم')),
                ('Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('worship_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion', to='HR.worshipsidesecond')),
            ],
            options={
                'verbose_name': 'رأي معد التقييم',
                'verbose_name_plural': 'رأي معد التقييم',
            },
        ),
        migrations.CreateModel(
            name='AlAbadiSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(blank=True, choices=[(1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449'), (1450, '1450'), (1451, '1451'), (1452, '1452'), (1453, '1453'), (1454, '1454'), (1455, '1455'), (1456, '1456'), (1457, '1457'), (1458, '1458'), (1459, '1459'), (1460, '1460'), (1461, '1461'), (1462, '1462'), (1463, '1463'), (1464, '1464'), (1465, '1465'), (1466, '1466'), (1467, '1467'), (1468, '1468'), (1469, '1469'), (1470, '1470'), (1471, '1471'), (1472, '1472'), (1473, '1473'), (1474, '1474'), (1475, '1475'), (1476, '1476'), (1477, '1477'), (1478, '1478'), (1479, '1479'), (1480, '1480'), (1481, '1481'), (1482, '1482'), (1483, '1483'), (1484, '1484'), (1485, '1485'), (1486, '1486'), (1487, '1487'), (1488, '1488'), (1489, '1489'), (1490, '1490'), (1491, '1491'), (1492, '1492'), (1493, '1493'), (1494, '1494'), (1495, '1495'), (1496, '1496'), (1497, '1497'), (1498, '1498'), (1499, '1499'), (1500, '1500')], null=True, verbose_name='السنة الهجرية')),
                ('gregorian_year', models.PositiveIntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True, verbose_name='السنة الميلادية')),
                ('hijri_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'محرم'), (2, 'صفر'), (3, 'ربيع الأول'), (4, 'ربيع الآخر'), (5, 'جمادى الأولى'), (6, 'جمادى الآخرة'), (7, 'رجب'), (8, 'شعبان'), (9, 'رمضان'), (10, 'شوال'), (11, 'ذو القعدة'), (12, 'ذو الحجة')], null=True, verbose_name='الشهر الهجري')),
                ('gregorian_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر الميلادي')),
                ('waking_up_before_dawn', models.IntegerField(verbose_name='الاستيقاظ قبل الفجر')),
                ('seeking_forgiveness', models.IntegerField(verbose_name='الاستغفار')),
                ('congregational_prayer', models.IntegerField(verbose_name='صلاة الجماعة')),
                ('maintaining_prayer', models.IntegerField(verbose_name='المحافظة على الصلاة')),
                ('the_supplication', models.IntegerField(verbose_name='الدعاء')),
                ('recitation_of_the_quran', models.IntegerField(verbose_name='تلاوة القرآن')),
                ('the_glorification', models.IntegerField(verbose_name='التسبيح')),
                ('friday_prayer', models.IntegerField(verbose_name='صلاة الجمعة')),
                ('interacted_with_the_lieutenant', models.IntegerField(verbose_name='التعامل مع الملازم')),
                ('the_truth_and_the_news', models.IntegerField(verbose_name='الحقيقة والأخبار')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='الإجمالي')),
                ('worship_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alabadi', to='HR.worshipsidesecond')),
            ],
            options={
                'verbose_name': 'عبادي',
                'verbose_name_plural': 'العبادي',
            },
        ),
    ]
