# Generated by Django 5.2.3 on 2025-12-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
