# Generated by Django 5.2.3 on 2025-12-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Present_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'الحضور',
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='السنة__')),
                ('month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='الشهر__')),
                ('Day1', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم_____ 1')),
                ('Day2', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 2')),
                ('Day3', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 3')),
                ('Day4', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 4')),
                ('Day5', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 5')),
                ('Day6', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 6')),
                ('Day7', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم_____ 7')),
                ('Day8', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 8')),
                ('Day9', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم____ 9')),
                ('Day10', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 10')),
                ('Day11', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 11')),
                ('Day12', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 12')),
                ('Day13', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 13')),
                ('Day14', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 14')),
                ('Day15', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 15')),
                ('Day16', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 16')),
                ('Day17', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 17')),
                ('Day18', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 18')),
                ('Day19', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 19')),
                ('Day20', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 20')),
                ('Day21', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 21')),
                ('Day22', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 22')),
                ('Day23', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 23')),
                ('Day24', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 24')),
                ('Day25', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 25')),
                ('Day26', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 26')),
                ('Day27', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 27')),
                ('Day28', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 28')),
                ('Day29', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 29')),
                ('Day30', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 30')),
                ('Day31', models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='م', max_length=2, verbose_name='اليوم___ 31')),
                ('present_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='HR.present_name', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'سجل الشهر',
                'verbose_name_plural': 'سجلات الأشهر',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
