# Generated by Django 5.2.3 on 2025-12-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_present_name_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='Day10',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 10'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day11',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 11'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day12',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 12'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day13',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 13'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day14',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 14'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day15',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 15'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day16',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 16'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day17',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 17'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day18',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 18'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day19',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 19'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day2',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 2'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day20',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 20'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day21',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 21'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day22',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 22'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day23',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 23'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day24',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 24'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day25',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 25'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day26',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 26'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day27',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 27'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day28',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 28'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day29',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 29'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day3',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 3'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day30',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 30'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day31',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم___ 31'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day4',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 4'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day5',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 5'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day6',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 6'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day7',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم_____ 7'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day8',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 8'),
        ),
        migrations.AlterField(
            model_name='present',
            name='Day9',
            field=models.CharField(choices=[('ح', 'ح'), ('م', 'م'), ('غ', 'غ'), ('د', 'د'), ('ذ', 'ذ'), ('هـ', 'ه')], default='ح', max_length=2, verbose_name='اليوم____ 9'),
        ),
        migrations.AlterField(
            model_name='present',
            name='month',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='الشهر______'),
        ),
        migrations.AlterField(
            model_name='present',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='السنة_________'),
        ),
    ]
