# Generated by Django 5.2.3 on 2025-12-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_alter_present_day1_alter_present_day10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_delegate', to='HR.person', verbose_name='المكلف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_follower', to='HR.person', verbose_name='المتابع'),
        ),
    ]
