# Generated by Django 5.2.3 on 2025-12-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_alter_task_delegate_alter_task_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='present_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='HR.present_name', verbose_name='الشخص'),
        ),
    ]
