# Generated by Django 5.2.3 on 2026-01-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_alter_present_day1_alter_present_day10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], verbose_name='السنة_________'),
        ),
        migrations.AlterField(
            model_name='student',
            name='learnyear',
            field=models.CharField(choices=[('ثانوي', 'ثانوي'), ('الأولى', 'الأولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة'), ('خريج', 'خريج')], max_length=10, verbose_name='السنة'),
        ),
    ]
