# Generated by Django 5.2.3 on 2026-01-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_alter_specialization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='present_name',
            name='device_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
