# Generated by Django 5.2.3 on 2026-01-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_present_name_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present_name',
            name='device_id',
        ),
    ]
