# Generated by Django 5.2.3 on 2026-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0017_alter_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الموظف في البصمة'),
        ),
    ]
