# Generated by Django 5.2.3 on 2026-02-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0018_name_device_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='device_user_id',
        ),
        migrations.AddField(
            model_name='name',
            name='zk_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم البصمة'),
        ),
    ]
