# Generated by Django 5.2.11 on 2026-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0020_alter_present_day1_alter_present_day10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='marital_status',
            field=models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], default='أعزب', max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='present',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='آخر يوم مزاور'),
        ),
    ]
