# Generated by Django 5.2.11 on 2026-04-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0021_name_marital_status_present_last_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='present',
            name='last_visit_date',
        ),
    ]
