# Generated by Django 5.2.11 on 2026-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0022_remove_name_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='marital_status',
            field=models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], default='أعزب', max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
    ]
