# Generated by Django 5.2.15 on 2026-06-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0024_alter_present_day1_alter_present_day10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ['-date', 'person'], 'verbose_name': 'سجل الحضور اليومي', 'verbose_name_plural': 'سجلات الحضور اليومية'},
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='person_name',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='الشخص'),
            preserve_default=False,
        ),
    ]
