# Generated by Django 5.2.15 on 2026-06-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0025_alter_dailyattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ['-date'], 'verbose_name': 'سجل الحضور اليومي', 'verbose_name_plural': 'سجلات الحضور اليومية'},
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='person',
        ),
        migrations.CreateModel(
            name='DailyAttendance_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'حضور يومي',
                'verbose_name_plural': 'الحضور اليومي',
            },
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='attendance_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HR.dailyattendance_name', verbose_name='سجل الشخص'),
            preserve_default=False,
        ),
    ]
