# Generated by Django 5.2.15 on 2026-06-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0026_alter_dailyattendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance_name',
            name='person',
        ),
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
        migrations.DeleteModel(
            name='DailyAttendance_name',
        ),
    ]
