# Generated by Django 5.2.15 on 2026-06-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0027_remove_dailyattendance_name_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.name', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'حضور يومي',
                'verbose_name_plural': 'الحضور اليومي',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2026, verbose_name='السنة')),
                ('month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='الشهر')),
                ('day_name', models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=10, verbose_name='اليوم')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.TimeField(verbose_name='وقت الدخول')),
                ('check_out', models.TimeField(verbose_name='وقت الخروج')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attendance_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.dailyattendance_name', verbose_name='سجل الشخص')),
            ],
            options={
                'verbose_name': 'سجل الحضور اليومي',
                'verbose_name_plural': 'سجلات الحضور اليومية',
                'ordering': ['-date'],
            },
        ),
    ]
