# Generated by Django 5.2.15 on 2026-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0028_dailyattendance_name_dailyattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance_name',
            options={'ordering': ['person__id'], 'verbose_name': 'حضور يومي', 'verbose_name_plural': 'الحضور اليومي'},
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='year',
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='day_name',
            field=models.CharField(blank=True, choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=10, verbose_name='اليوم'),
        ),
    ]
