# Generated by Django 5.2.15 on 2026-06-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0029_alter_dailyattendance_name_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance_name',
            options={'ordering': ['person__first_name'], 'verbose_name': 'حضور يومي', 'verbose_name_plural': 'الحضور اليومي'},
        ),
    ]
