# Generated by Django 5.2.15 on 2026-07-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0030_alter_dailyattendance_name_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmakeropinionsecond',
            name='worship_side',
        ),
        migrations.RemoveField(
            model_name='behavioralsecond',
            name='worship_side',
        ),
        migrations.RemoveField(
            model_name='culturalsecond',
            name='worship_side',
        ),
        migrations.RemoveField(
            model_name='generalnotessecond',
            name='worship_side',
        ),
        migrations.RemoveField(
            model_name='strengthandweaknesssecond',
            name='worship_side',
        ),
        migrations.RemoveField(
            model_name='worshipsidesecond',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Polarized_sid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='person',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='person',
            name='jihadist_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='military_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='AlAbadiSecond',
        ),
        migrations.DeleteModel(
            name='AssessmentMakerOpinionSecond',
        ),
        migrations.DeleteModel(
            name='BehavioralSecond',
        ),
        migrations.DeleteModel(
            name='CulturalSecond',
        ),
        migrations.DeleteModel(
            name='GeneralNotesSecond',
        ),
        migrations.DeleteModel(
            name='StrengthAndWeaknessSecond',
        ),
        migrations.DeleteModel(
            name='WorshipSideSecond',
        ),
    ]
