# Generated by Django 5.2.15 on 2026-07-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0031_remove_assessmentmakeropinionsecond_worship_side_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظف'},
        ),
    ]
