"""
Django settings for HR project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(ecaqk1-13#*kmh2x6kczd80^yeuvri6yay^5$(coj8l0f)l5o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    
    "django_daisy",
    "django.contrib.admin",
    "django.contrib.humanize",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    'django_extensions',
    "HR",
    'bootstrap_datepicker_plus',
]


MIDDLEWARE = [
    

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware',

]

ROOT_URLCONF = "HR.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": True,
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HR.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hr_db',       
        'USER': 'postgres',   
        'PASSWORD': '774815916',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

DAISY_SETTINGS = {
    "site_header": "نظام ادراة الموارد البشرية",
    "site_title": "لوحة تحكم | نظام ادراة الموارد البشرية",
    "index_title": "نظام ادراة الموارد البشرية",
    'SITE_LOGO': '/static/logo.png',
    
    'EXTRA_STYLES': [
        '/static/css/custom-admin.css',
        '/static/admin/css/sticky_headers.css',
        
    ],
    'DONT_SUPPORT_ME': True,
    'APPS_REORDER': {
      'HR': {
        'icon': 'fa-solid fa-briefcase',
        'name': 'الموارد البشرية',
        'divider_title': "النظام",
     },
        'auth': {
            'icon': 'fa-solid fa-user-shield',  # أيقونة FontAwesome جديدة
            'name': 'المستخدمون والصلاحيات',  
            'hide': False,  
            'divider_title': "المستخدمون",  
        },
        'Dashboard': {
            'icon': 'fa-solid fa-gears',  
            'name': 'لوحة الإدارة',  
        },
        'sessions': {
            'icon': 'fa-solid fa-clock',  
            'name': 'الجلسات',  
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES_CODE ="ar"
# LANGUAGES = [
    
#     ('ar', 'Arabic'),
#     ('en', 'English'),
#     # Add other languages as needed
# ]
TIME_ZONE = "Asia/Aden"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # لتجميع كل ملفات static هنا
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
  # هذا المسار لمجلد static داخل التطبيق
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"




